[package]
name = "scx-terminal"
version = "0.1.0"
description = "scx-terminal — a terminal built with Tauri V2"
edition = "2021"

[lib]
name = "scx_terminal_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["macos-private-api"] }
tauri-plugin-opener = "2"
tauri-plugin-clipboard-manager = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
portable-pty = "0.9"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "io-util", "net", "sync", "time"] }
uuid = { version = "1", features = ["v4"] }
window-vibrancy = "0.6"
font-loader = "0.11.0"
russh = "0.63.3"
rusqlite = { version = "0.40.2", features = ["bundled"] }
aes-gcm = "0.11.1"
keyring = "4.2.0"
getrandom = "0.3"
russh-sftp = "3.0.0"
fast-socks5 = "1.0"
tauri-plugin-dialog = "2.7.3"

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
strip = true
